name: CI Tests

on:
    push:
    pull_request:

jobs:
    run-tests:
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                php: [ "7.2", "7.3", "7.4", "8.0", "8.1", "8.2" ]
                composer_flags: [ "", "--prefer-lowest" ]
                symfony_version: [ "^3.4", "^4.4", "^5.4", "^6.3"]
                exclude:
                  - php: "7.2"
                    symfony_version: "^6.3"
                  - php: "7.3"
                    symfony_version: "^6.3"
                  - php: "7.4"
                    symfony_version: "^6.3"
                  - php: "8.0"
                    symfony_version: "^6.3"
                  - php: "8.2"
                    symfony_version: "^4.4"
        name: PHP ${{ matrix.php }} SF ${{ matrix.symfony_version }} ${{ matrix.composer_flags}}
        env:
            PHP: ${{ matrix.os }}
            COMPOSER_MEMORY_LIMIT: -1
            COMPOSER_FLAGS: ${{ matrix.composer_flags }}
            SYMFONY_VERSION: ${{ matrix.symfony_version }}
            PHP_VERSION: ${{ matrix.php }}
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}
                extensions: redis
                ini-values: memory_limit=256M,post_max_size=256M
            - name: Checkout ratelimit bundle
              uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                composer self-update
                if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
                if [ "$SYMFONY_VERSION" = "^5.4" ] || [ "$SYMFONY_VERSION" = "^6.3" ] ||  [ "$PHP_VERSION" = "8.0" ] || [ "$PHP_VERSION" = "8.1" ] || [ "$PHP_VERSION" = "8.2" ]; then composer remove --dev "friendsofsymfony/oauth-server-bundle" --no-update; fi;
                COMPOSER_MEMORY_LIMIT=-1 composer update --prefer-dist --no-interaction $COMPOSER_FLAGS
            - name: Run tests
              run: |
                SYMFONY_DEPRECATIONS_HELPER=weak vendor/bin/simple-phpunit
